const imageFilesPreload = [
    {name: 'whitePixel', src: 'sprites/preload/white_pixel.png'},
    {name: 'blackPixel', src: 'sprites/preload/black_pixel.png'},
    {name: 'loadingSpinner', src: 'sprites/preload/loading_spinner.png'},
    {name: 'castNormal', src: 'sprites/preload/cast_normal.png'},
    {name: 'introLocket', src: 'sprites/preload/locket.webp'},

    {name: 'runeEnhancePre', src: 'sprites/preload/rune_enhance_glow.png'},
    {name: 'runeMatterPre', src: 'sprites/preload/rune_matter_glow.png'},
    {name: 'runeMindPre', src: 'sprites/preload/rune_mind_glow.png'},
    {name: 'runeProtectPre', src: 'sprites/preload/rune_protect_glow.png'},
    {name: 'runeReinforcePre', src: 'sprites/preload/rune_reinforce_glow.png'},
    {name: 'runeStrikePre', src: 'sprites/preload/rune_strike_glow.png'},
    {name: 'runeTimePre', src: 'sprites/preload/rune_time_glow.png'},
    {name: 'runeUnloadPre', src: 'sprites/preload/rune_unload_glow.png'},
    {name: 'runeVoidPre', src: 'sprites/preload/rune_void_glow.png'},

];

// All sprite atlases are defined in the single file sprites/atlases.json
// (loaded by loadAtlases() in main.js). A human-readable inventory of every
// frame lives in spriteManifest.js (regenerated by scripts/genSpriteManifest.js).
const imageAtlases = [
    'backgrounds',
    'blurry',
    'buttons',
    'circle',
    'deathfin',
    'deathfinal',
    'dummyenemy',
    'ending',
    'enemies',
    'lowq',
    'misc',
    'pixels',
    'shields',
    'spells',
    'tutorial',
    'ui',
    'wallenemy',
    'water',
];

// Atlases loaded in the background after the game starts
const deferredImageAtlases = [
    'ending',
    'deathfin',
    'wallenemy',
    'deathfinal',
];

const imageFiles = [
];

const videoFiles = [
];
